apiVersion: policies.kubewarden.io/v1alpha2
kind: ClusterAdmissionPolicy
metadata:
  name: required-owner-team
spec:
  module: registry://registry.ereslibre.net/kubewarden/policies/requiredlabels:latest
  rules:
  - apiGroups:
    - networking.k8s.io
    apiVersions:
    - v1
    resources:
    - ingresses
    operations:
    - CREATE
    - UPDATE
  mutating: false
  settings:
    labels:
    - key: owner-team
